# Generated by Django 4.1 on 2022-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=50)),
                ('people_group', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
